version: '3'
services:
  app:
    image: lucidtaz/reversi-app
    build:
      dockerfile: docker/images/app/Dockerfile
      context: .
    volumes:
      # Use local directory for faster development
      - ./:/reversi
  web:
    image: lucidtaz/reversi-web
    build:
      dockerfile: docker/images/web/Dockerfile
      context: .
    ports:
    - "8080:80"
    volumes:
      # Use local directory for faster development
      - ./app/public:/reversi/app/public
